# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='open',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
