# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_web', '0002_article_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='item_id',
            new_name='item',
        ),
    ]
