# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_web', '0005_auto_20181205_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(default='未命名', max_length=50),
        ),
        migrations.AddField(
            model_name='admin',
            name='tel',
            field=models.CharField(default='', max_length=11),
        ),
    ]
